### ISSUE TITLE
💗 the User Settings!

### ISSUE THREAD

**Issue by PySimpleGUI** [kcl1s/Hand-Gestures#1]
You made my evening tonight!

![image](https://user-images.githubusercontent.com/46163555/185770844-07475fc0-33a9-4d48-b977-35e6cc29d6d8.png)

I was just about to stop for the night when I saw your project. I saw the JSON file and assumed that like 99% of the programs on GitHub, including PySimpleGUI ones, I would see an import of json at the top of the code.  Not only did I not see a json import, but it's a PySimpleGUI program too.... And, it's one that's using the User Settings alls to access JSON data.  Was a great little surprise ending for the day.  Sometimes it's the little things, ya know?

![image](https://user-images.githubusercontent.com/46163555/185771017-7916735c-87fe-452d-bd1b-b3841a8be718.png)

**Comment by kcl1s** [comment]
Thanks, I put screenshots of this up on the pySimpleGUI Post your screen shots here! page a while back. I just added links to a couple of explainer videos I made as homework for an online Python class I was taking. Not too bad for a newbie Python hobby coder if I do say so myself.

**Comment by PySimpleGUI** [comment]
Oooo!  NICE!  Thank you for adding both the screnshot and the videos.... it's going to help visitors a lot!
